### PR TITLE
Add typings to the repo

### PR DESCRIPTION
**Pull request by unional**
Do you want to add more comments added? :smile:

### CODE REVIEW

**Comment by sindresorhus** [comment]
Add it to https://github.com/DefinitelyTyped/DefinitelyTyped instead. I'm not interested in maintaining typings for something I don't use. Thanks though :)

**Comment by unional** [comment]
No problem. 🌷

**Comment by SamVerschueren** [comment]
And it already exists https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/path-exists

**Comment by unional** [comment]
Yes, but having the typings inside the source would help user so that they don't have to manually download and install it (either from DT directly, `tsd`, `typings`, or `npm install @types/path-exists`).

Also, the version I put in here is in external module format. The one in DT is not and need to be converted.

I put it here https://github.com/types/npm-path-exists and register it at https://github.com/typings/registry so that user can install it with `typings install path-exists`.

**Comment by unional** [comment]
by the way, you can see the version in DT is outdated anyway, it's in callback form.

**Pull request closed without merging**
